name: Deliver Next Part

on:
  issue_comment:
    types: [created]

jobs:
  deliver-next-part:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/start-part')
    steps:
      - name: Parse command
        id: parse
        run: |
          # The /start-part command must be in a comment
          COMMENT="${{ github.event.comment.body }}"

          if [[ "$COMMENT" == /start-part* ]]; then
            CMD="$COMMENT"
          else
            echo "No /start-part command found in comment. Exiting."
            exit 0
          fi
          # Extract the part number to start
          PART_TO_START=$(echo $CMD | awk '{print $2}')
          if [[ -z "$PART_TO_START" ]]; then
            echo "Malformed command. Usage: /start-part <part-number>"
            exit 0
          fi
          # Convert to integer to handle leading zeros
          PART_TO_START_INT=$((10#$PART_TO_START))
          PREVIOUS_PART_INT=$((PART_TO_START_INT - 1))

          # Format with leading zeros for branch names
          PART_TO_START_PADDED=$(printf "%03d" $PART_TO_START_INT)
          PREVIOUS_PART_PADDED=$(printf "%03d" $PREVIOUS_PART_INT)

          echo "part_to_start=$PART_TO_START_INT" >> $GITHUB_OUTPUT
          echo "previous_part=$PREVIOUS_PART_INT" >> $GITHUB_OUTPUT
          echo "part_to_start_padded=$PART_TO_START_PADDED" >> $GITHUB_OUTPUT
          echo "previous_part_padded=$PREVIOUS_PART_PADDED" >> $GITHUB_OUTPUT

      - name: Get student repo from issue
        id: get_student_repo
        run: |
          # Get the original issue title and body to find the create-student-repo command
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"

          # Check title first, then body for the start-challenge command
          if [[ "$ISSUE_TITLE" == /start-challenge* ]]; then
            CMD="$ISSUE_TITLE"
          elif [[ "$ISSUE_BODY" == /start-challenge* ]]; then
            CMD="$ISSUE_BODY"
          else
            echo "Error: Could not find /start-challenge command in issue title or body"
            echo "Issue title: $ISSUE_TITLE"
            echo "Issue body: $ISSUE_BODY"
            exit 1
          fi

          # Extract project name (username comes from issue author)
          PROJECT=$(echo "$CMD" | awk '{print $2}')
          if [[ -z "$PROJECT" ]]; then
            echo "Error: Could not parse project from command"
            echo "Command: $CMD"
            exit 1
          fi

          # Get username from issue author
          USERNAME="${{ github.event.issue.user.login }}"

          # Construct the student repo name
          STUDENT_REPO="TimKingtonFC/${PROJECT}-${USERNAME}"
          echo "student_repo=$STUDENT_REPO" >> $GITHUB_OUTPUT
          echo "username=$USERNAME" >> $GITHUB_OUTPUT

      - name: Validate user permissions
        id: validate_user
        if: steps.parse.outputs.part_to_start_padded && steps.get_student_repo.outputs.student_repo
        run: |
           # Get the username from the original issue (who started the challenge)
           ORIGINAL_USERNAME="${{ steps.get_student_repo.outputs.username }}"
           # Get the comment author (who is requesting the next part)
           COMMENT_USERNAME="${{ github.event.comment.user.login }}"

           if [[ "$ORIGINAL_USERNAME" != "$COMMENT_USERNAME" ]]; then
             echo "❌ **Access Denied!**"
             echo ""
             echo "Only the original student (@$ORIGINAL_USERNAME) can request the next part."
             echo "Current user: @$COMMENT_USERNAME"
             exit 1
           fi

           echo "✅ User validation passed. @$COMMENT_USERNAME is authorized."

      - name: Push solution and starter branches
        if: steps.parse.outputs.part_to_start_padded && steps.get_student_repo.outputs.student_repo && steps.validate_user.outcome == 'success'
        run: |
          # Clone the main repo as a bare repository
          git clone --bare https://${{ secrets.ADMIN_GITHUB_TOKEN }}@github.com/TimKingtonFC/chaltest.git mirror
          cd mirror

          # Push previous part solution branch
          git push https://${{ secrets.ADMIN_GITHUB_TOKEN }}@github.com/${{ steps.get_student_repo.outputs.student_repo }}.git part${{ steps.parse.outputs.previous_part_padded }}-solution:part${{ steps.parse.outputs.previous_part_padded }}-solution

          # Push part to start starter branch
          git push https://${{ secrets.ADMIN_GITHUB_TOKEN }}@github.com/${{ steps.get_student_repo.outputs.student_repo }}.git part${{ steps.parse.outputs.part_to_start_padded }}-starter:part${{ steps.parse.outputs.part_to_start_padded }}-starter

          # Create part to start work branch from starter
          git push https://${{ secrets.ADMIN_GITHUB_TOKEN }}@github.com/${{ steps.get_student_repo.outputs.student_repo }}.git part${{ steps.parse.outputs.part_to_start_padded }}-starter:part${{ steps.parse.outputs.part_to_start_padded }}-work

          # Clean up
          cd ..
          rm -rf mirror

      - name: Set default branch to part to start work
        if: steps.parse.outputs.part_to_start_padded && steps.get_student_repo.outputs.student_repo
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.ADMIN_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ steps.get_student_repo.outputs.student_repo }} \
            -d '{"default_branch": "part${{ steps.parse.outputs.part_to_start_padded }}-work"}'

      - name: Comment with result
        if: steps.get_student_repo.outputs.student_repo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            const student_repo = '${{ steps.get_student_repo.outputs.student_repo }}';
            const part_to_start = '${{ steps.parse.outputs.part_to_start }}';
            const repo_url = `https://github.com/${student_repo}`;

            await github.rest.issues.createComment({
              ...context.repo,
              issue_number,
              body: `✅ Part ${part_to_start} delivered to ${repo_url}.`
            });

      - name: Comment on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;

            // Determine which step failed
            let failedStep = 'Unknown step';
            let errorMessage = 'Please check the workflow logs for details and try again.';

            if ('${{ steps.parse.outcome }}' === 'failure') {
              failedStep = 'Command parsing';
            } else if ('${{ steps.get_student_repo.outcome }}' === 'failure') {
              failedStep = 'Finding student repository';
            } else if ('${{ steps.validate_user.outcome }}' === 'failure') {
              failedStep = 'User validation';
              errorMessage = 'Only the original student can request the next part.';
            } else if ('${{ steps.push_branches.outcome }}' === 'failure') {
              failedStep = 'Pushing branches';
            } else if ('${{ steps.set_default.outcome }}' === 'failure') {
              failedStep = 'Setting default branch';
            }

            await github.rest.issues.createComment({
              ...context.repo,
              issue_number,
              body: `❌ **Workflow failed!**\n\nFailed at: ${failedStep}\n\n${errorMessage}`
            });
